### PR TITLE
Integrate docker into aws_locker

### PR DESCRIPTION
**Pull request by darbym**
This PR creates a Ubuntu container to run aws_locker from and it mounts the user's local ~/.aws directory into the container for use.

### CODE REVIEW

**Review by martinka — COMMENTED** [review]
Is there a way to run the test cases in Docker?  If not no big deal, just curious.

**Comment by darbym** [comment]
Let me check.

**Comment by darbym** [comment]
Added running of test inside the container.

**Review by martinka — APPROVED** [review]
Looks good to me.

**Pull request merged**
